name: macOS

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: artifact
        run: |
          brew install cmake llvm
          brew outdated llvm || brew upgrade llvm
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/artifacts -DCMAKE_PREFIX_PATH=$(brew --prefix llvm)
          make install -j4
      - uses: actions/upload-artifact@v2
        with:
          name: zig-latest-macOS
          path: artifacts
